import { Inter } from "next/font/google";
import StyledComponentsRegistry from "./lib/StyledComponentsRegistry";
import GlobalThemeProvider from "./lib/GlobalThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js Styled-Components App",
  description: "Generated by create-next-styled-app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <GlobalThemeProvider>{children}</GlobalThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
